version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  mico-detour-node:
    lang: node
    handler: ./mico-detour-node
    image: zwickel/mico-detour-node:latest
    # environment: 
    #   redis: openfaas-redis-master
